### ISSUE TITLE
可否为主库适配下

### ISSUE THREAD

**Issue by fuqiang03** [NateLol/luci-app-beardropper#1]
可否为主库适配下
无法在master运行

**Comment by NateLol** [comment]
什么意思？
我在Readme中添加了compile说明

**Comment by fuqiang03** [comment]
在主库的控制页面下点接受按钮后没有启动成功 必须使用命令才能启动脚本

**Comment by NateLol** [comment]
我增加了ACL rule，你可以试试看能不能work。
可以了告诉我，我关掉这个issue，谢谢！

**Comment by fuqiang03** [comment]
没有acl规则是无法看到配置界面的

**Comment by fuqiang03** [comment]
我重新编译一次试试

**Comment by NateLol** [comment]
你等等，可能还需要加一个menu.d

**Comment by fuqiang03** [comment]
好的

**Comment by fuqiang03** [comment]
感觉还是使用luci 的mk能舒服些

**Comment by NateLol** [comment]
master分支已经可以直接用feeds 编译了，但是你得自己做个本地feeds，在`feeds.conf`或者`feeds.conf.default`中用src-link加进去。
同样也使用了luci.mk。

另外一个branch openwrt19.07直接按照说明编译就可以了。



> 在主库的控制页面下点接受按钮后没有启动成功 必须使用命令才能启动脚本

这个问题，我之前使用的不是ucitrack，而是在cbi里面写了服务重启的命令，讲道理应该没有问题的。
现在换成了ucitrack，我测试是没有问题的，你再看看。

**Comment by fuqiang03** [comment]
![QQ截图20200522214144](https://user-images.githubusercontent.com/26851715/82673939-268b6e00-9c75-11ea-8de4-1ff04deb5adb.png)

m:section(SimpleSection).template="beardropper/status"
m:section(SimpleSection).template="bearDropper/status"差个d 字母大小写 acl规则 可以正常运行了
cat 的错误提示未忽略

![QQ截图20200522214849](https://user-images.githubusercontent.com/26851715/82674591-20e25800-9c76-11ea-83b2-e824cde15319.png)
